sudo: required

env:
  global:
    - DOCKER_IMAGE=levgogol/cicd-buzz

services:
  - docker

language: python

python: 2.6.7

cache:
  pip: false

script:
  - python -m pytest -v

after_success:
  - sh .travis/upload_to_dockerhub.sh
