sudo: required

env:
  global:
    - DOCKER_IMAGE=levgogol/cicd-buzz

services:
  - docker

language: python

python: 3.6.7

install:
  - pip install codecov

test:
  - python -m pytest -v

upload:
  - sh .travis/upload_to_dockerhub.sh

deploy:
  - sh .travis/deploy_to_server.sh
